Repository kraken-build/kraken-std, pull requests merged in 2023-02, with the labels that each got.

#85 use Slap GitHub actions to verify added changelogs and update changel…
  .github/workflows/python-package.yml
Labels: no changelog

#88 Update python-package.yml
  .github/workflows/python-package.yml
Labels: no changelog

#91 Don't try to pyupgrade files that don't exist
  .changelog/_unreleased.toml
  src/kraken/std/python/tasks/pyupgrade_task.py
Labels: bug

#94 Ditch Vault to make collaboration easier
  .github/workflows/python-package.yml
  src/tests/integration/cargo/test_cargo_private_registry.py
Labels: no changelog

#101 improvement: Enable `pytest --doctest-modules` flag (controlled by `PytestTask.doctest_modules`, enabled by default).
  .changelog/_unreleased.toml
  src/kraken/std/cargo/tasks/__init__.py
  src/kraken/std/descriptors/__init__.py
  src/kraken/std/git/tasks/__init__.py
  src/kraken/std/python/tasks/__init__.py
  src/kraken/std/python/tasks/pytest_task.py
Labels: enhancement
